services:
  wg-easy:
    environment:
      # ‚ö†Ô∏è REQUIRED: Change this to your VPS's public IP or domain
      - WG_HOST
      # ‚ö†Ô∏è REQUIRED: Web UI Password Hash
      - PASSWORD_HASH
      # Optional:
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=51821
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_MTU=1200
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE; iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -j MASQUERADE; iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=0
      # üé® OPTIONAL: Custom UI Title
      - UI_TITLE=${UI_TITLE:-SE2 VPN}
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    privileged: true
    volumes:
      - wg-data:/etc/wireguard
      # üñºÔ∏è OPTIONAL: Custom Logo (Requires a logo.svg file in this directory)
      # - ./custom-logo.svg:/app/public/img/logo.svg
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      - dokploy-network

volumes:
  wg-data:


networks:
  dokploy-network:
    external: true
